# -*- coding: utf-8 -*-
"""test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tj2niiwpZy0v1eGLio2l6t4R87knkKl_
"""

from source import object
t = object(1)
print(t)